name: former_gen
description: Code generation for former.
version: 0.2.1
homepage: https://github.com/kennethnym/former_gen

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.0.0
  build: ^2.0.1
  source_gen: ^1.0.0
